name: Build Go Application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Build
        run: |
          CGO_ENABLED=0 go build -o myapp .
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: myapp
